name: im2recipe
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - numpy
  - tqdm
  - torchfile
  - simplejson
  - python-lmdb
  - word2vec
  - scipy=1.1.0
  - pillow!=8.3.0
  - pytorch=1.9.0
  - torchvision
  - cudatoolkit=11.1
